#服务器配置
server:
  port: 8080
#项目配置
spring:
  #环境指定
  profiles:
    active: pro
  #资源配置
  thymeleaf:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #时间格式配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  #jpa配置
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  #最大上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB