#服务器配置
server:
  port: 8080
  tomcat:
      basedir: /usr/tomcat/temp
      uri-encoding: utf-8
      max-connections: 2000
      max-threads: 2000
#项目配置
#不分表数据源配置，注意修改启动类和sysLogDO主键生成策略
#spring:
#  #数据连接配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://xxx.xx.xx.xx:3306/yyms?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: xxx
#    password: xxx
# 分表配置
spring:
  shardingsphere:
    datasource:
      names: yyms
      yyms:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://xxx.xx.xx.xx:3306/yyms?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: xx
        password: xxx
    sharding:
      tables:
        sys_log:
          actual-data-nodes: yyms.sys_log_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: sys_log_$->{id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql:
        show: true
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
