#服务器配置
server:
  port: 8080
  tomcat:
      basedir: /usr/tomcat/temp
      uri-encoding: utf-8
      max-connections: 2000
      max-threads: 2000
#项目配置
spring:
  #数据连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxx/xxxxxx?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      username: xxxx
      password: xxxxx
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
