#服务器配置
server:
  port: 8080
#项目配置
spring:
  #数据连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxx/xxxxxx?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      username: xxxx
      password: xxxxx
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
      location: /usr/tomcat/temp
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace